default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: community_development
  username: community_user
  password: community5310

test:
  <<: *default
  database: community_test
  username: community_user
  password: community5310

production:
  <<: *default
  database: community_production
  username: community_user
  password: community_us3r
