source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.4.5'
gem 'rails', '5.2.2'
gem 'pg', '1.0.0'
gem 'puma', '4.3.12'
gem 'uglifier', '4.1.20'
# gem 'mini_racer', platforms: :ruby
gem 'turbolinks', '5.2.0'
gem 'jbuilder', '2.8.0'
gem 'jquery-rails', '4.3.3'
gem 'jquery-ui-rails'
gem 'popper_js'
gem 'bootsnap', '1.3.2', require: false
gem 'kaminari', '1.1.1'
gem 'rake', '12.3.2'
gem 'bootstrap4-datetime-picker-rails', '0.3.1'
gem 'momentjs-rails', '2.20.1'
group :development do
  gem 'web-console', '3.7.0'
  gem 'listen', '3.1.5'
  gem 'spring', '2.0.2'
  gem 'spring-watcher-listen', '2.0.1'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'devise', '4.6.2'

gem 'wdm', '0.1.1' if Gem.win_platform?
gem 'rails4-autocomplete', '1.1.1'